## Web scrapping assignment-4 (selenium)

In [1]:
# Importing Libraries
import selenium
import pandas as pd
import time
from bs4 import BeautifulSoup

# Importing selenium webdriver 
from selenium import webdriver

# Importing required Exceptions which needs to handled
from selenium.common.exceptions import StaleElementReferenceException, NoSuchElementException

#Importing requests
import requests

# importing regex
import re

Q1. Scrape the details of most viewed videos on YouTube from Wikipedia.
Url = https://en.wikipedia.org/wiki/List_of_most-viewed_YouTube_videos
You need to find following details:
A) Rank
B) Name
C) Artist
D) Upload date
E) Views

In [2]:
# connect to webdriver
driver=webdriver.Chrome(r"C:\Users\user\Desktop\chromedriver_win32_new\chromedriver.exe") 
time.sleep(2)

# to get url
url = " https://en.wikipedia.org/wiki/List_of_most-viewed_YouTube_videos"
driver.get(url)
time.sleep(2)

In [4]:
#empty list
name=[]
rank=[]
artist=[]
views=[]
upload_date=[]

# to scrape names of the videos
try:
    names=driver.find_elements_by_xpath("//table[@class='wikitable sortable jquery-tablesorter'][1]/tbody/tr/td[2]")
    for i in names:
        name.append(i.text)
except NoSuchElementException:
    name.append('-')
except StaleElementReferenceException:
    name.append('-')
    
time.sleep(2)    
# to scrape rank of the videos
try:
    ranks=driver.find_elements_by_xpath("//table[@class='wikitable sortable jquery-tablesorter'][1]/tbody/tr/td[1]")
    for i in ranks:
        rank.append(i.text)
except NoSuchElementException:
    rank.append('-')
except StaleElementReferenceException:
    rank.append('-')

time.sleep(2)
#to scrape uploader details

try:
    artists=driver.find_elements_by_xpath("//table[@class='wikitable sortable jquery-tablesorter'][1]/tbody/tr/td[3]")
    for i in artists:
        artist.append(i.text)
except NoSuchElementException:
    artist.append('-')
except StaleElementReferenceException:
    artist.append('-')
    
time.sleep(2)    
# to scrape views of the videos

try:
    views_list=driver.find_elements_by_xpath("//table[@class='wikitable sortable jquery-tablesorter'][1]/tbody/tr/td[4]")
    for i in views_list:
        views.append(i.text)
except NoSuchElementException:
    views.append('-')
except StaleElementReferenceException:
    views.append('-')
    
time.sleep(2)    
#to scrape date of upload

try:
    upload_date_list=driver.find_elements_by_xpath("//table[@class='wikitable sortable jquery-tablesorter'][1]/tbody/tr/td[5]")
    for i in upload_date_list:
        upload_date.append(i.text)
        
except NoSuchElementException:#handling no such element exception
    upload_date.append('-')
except StaleElementReferenceException:#handling Stale element exception
    upload_date.append('-')
    
time.sleep(2)    

#to make dataframe
df=pd.DataFrame({"Rank":rank,
                 "Name":name,
                "Uploader/artist":artist,
                "Date of upload":upload_date,
                "Views(in billion)":views})
df

,Rank,Name,Uploader/artist,Date of upload,Views(in billion)
0,1.,"""Baby Shark Dance""[3]",Pinkfong Baby Shark - Kids' Songs & Stories,"June 17, 2016",10.70
1,2.,"""Despacito""[6]",Luis Fonsi,"January 12, 2017",7.85
2,3.,"""Johny Johny Yes Papa""[12]",LooLoo Kids,"October 8, 2016",6.35
3,4.,"""Shape of You""[13]",Ed Sheeran,"January 30, 2017",5.72
4,5.,"""See You Again""[15]",Wiz Khalifa,"April 6, 2015",5.51
5,6.,"""Bath Song""[20]",Cocomelon – Nursery Rhymes,"May 2, 2018",5.38
6,7.,"""Phonics Song with Two Words""[21]",ChuChu TV,"March 6, 2014",4.63
7,8.,"""Uptown Funk""[22]",Mark Ronson,"November 19, 2014",4.57
8,9.,"""Learning Colors – Colorful Eggs on a Farm""[23]",Miroshka TV,"February 27, 2018",4.57
9,10.,"""Masha and the Bear – Recipe for Disaster""[24]",Get Movies,"January 31, 2012",4.50
10,11.,"""Gangnam Style""[25]",Psy,"July 15, 2012",4.43
11,12.,"""Wheels on the Bus""[30]",Cocomelon – Nursery Rhymes,"May 24, 2018",4.07
12,13.,"""Dame Tu Cosita""[31]",El Chombo,"April 5, 2018",3.94
13,14.,"""Sugar""[32]",Maroon 5,"January 14, 2015",3.70
14,15.,"""Roar""[33]",Katy Perry,"September 5, 2013",3.58
15,16.,"""Counting Stars""[34]",OneRepublic,"May 31, 2013",3.58
16,17.,"""Sorry""[35]",Justin Bieber,"October 22, 2015",3.55
17,18.,"""Thinking Out Loud""[36]",Ed Sheeran,"October 7, 2014",3.45
18,19.,"""Axel F""[37]",Crazy Frog,"June 16, 2009",3.36
19,20.,"""Girls Like You""[38]",Maroon 5,"May 31, 2018",3.29
20,21.,"""Faded""[39]",Alan Walker,"December 3, 2015",3.28
21,22.,"""Dark Horse""[40]",Katy Perry,"February 20, 2014",3.27
22,23.,"""Baa Baa Black Sheep""[41]",Cocomelon – Nursery Rhymes,"June 25, 2018",3.24
23,24.,"""Let Her Go""[42]",Passenger,"July 25, 2012",3.23
24,25.,"""Bailando""[43]",Enrique Iglesias,"April 11, 2014",3.21
25,26.,"""Lean On""[44]",Major Lazer,"March 22, 2015",3.21
26,27.,"""Shake It Off""[45]",Taylor Swift,"August 18, 2014",3.17
27,28.,"""Perfect""[46]",Ed Sheeran,"November 9, 2017",3.17
28,29.,"""Waka Waka (This Time for Africa)""[47]",Shakira,"June 4, 2010",3.14
29,30.,"""Mi Gente""[48]",J Balvin,"June 29, 2017",3.08

In [11]:
driver.close

Q2. Scrape the details team India’s international fixtures from bcci.tv.
Url = https://www.bcci.tv/.
You need to find following details:
A) Match title (I.e. 1st ODI)
B) Series
C) Place
D) Date
E) Time
Note: - From bcci.tv home page you have reach to the international fixture page through code.

In [ ]:
# connect to webdriver
driver=webdriver.Chrome(r"C:\Users\user\Desktop\chromedriver_win32_new\chromedriver.exe") 
time.sleep(2)

# to get url
url = "  https://www.bcci.tv/"
driver.get(url)
time.sleep(2)

time.sleep(2)
#going to international fixtures page
fixtures=driver.find_element_by_xpath("//li[@class='nav-item ml-0']")
try:
    fixtures.click()
except ElementNotInteractableException:
    driver.get(fixtures.get_attribute('href'))
    

#Creating empty list
Match_title = []
Series = []
Place = []
Date = []
Time = []


#Scraping data of series name
for i in driver.find_elements_by_xpath("//h5[@class='fix-text']//span"):
    Series.append(i.text)
Series

#Scraping data of match title
for i in driver.find_elements_by_xpath("//div[@class='fixture-card-bottom']//span"):
    Match_title.append(i.text)
Match_title[::2]

#Scraping data of Place
for i in driver.find_elements_by_xpath("//div[@class='fixture-card-bottom']"):
    Place.append(i.text)
Place

place1=[]

for i in Place:
    i=i.strip("\nMatch Centre")
    i=i.strip("-")[10:]
    place1.append(i)
place1

#Scraping data of the match date
for i in driver.find_elements_by_xpath("//div[@class='match-card-left match-schedule']//h5"):
    Date.append(i.text)
Date

#Scraping data of the match timing
for i in driver.find_elements_by_xpath("//div[@class='match-card-right match-schedule ']//h5"):
    Time.append(i.text)
Time

In [155]:
#DATA FRAMEING
BCCI=pd.DataFrame({})
BCCI['Match Title'] = Match_title[::2]
BCCI['Series'] = Series[1::2]
BCCI['Place'] = place1
BCCI['Date'] = Date
BCCI['Time'] = Time
BCCI

,Match Title,Series,Place,Date,Time
0,1st T20I -,SOUTH AFRICA TOUR OF INDIA T20 SERIES 2022,"Arun Jaitley Stadium, Delhi",9 JUN 2022,7:00 PM IST
1,2nd T20I -,SOUTH AFRICA TOUR OF INDIA T20 SERIES 2022,"Barabati Stadium, Cuttack",12 JUN 2022,7:00 PM IST
2,3rd T20I -,SOUTH AFRICA TOUR OF INDIA T20 SERIES 2022,Dr YS Rajasekhara Reddy ACA-VDCA Cricket Stad...,14 JUN 2022,7:00 PM IST
3,4th T20I -,SOUTH AFRICA TOUR OF INDIA T20 SERIES 2022,"Saurashtra Cricket Association Stadium, Rajko",17 JUN 2022,7:00 PM IST
4,5th T20I -,SOUTH AFRICA TOUR OF INDIA T20 SERIES 2022,"M Chinnaswamy Stadium, Bengaluru",19 JUN 2022,7:00 PM IST

In [156]:
driver.close

Q3. Scrape the details of selenium exception from guru99.com.
Url = https://www.guru99.com/
You need to find following details:
A) Name
B) Description
Note: - From guru99 home page you have to reach to selenium exception handling page through code

In [143]:
# connect to webdriver
driver=webdriver.Chrome(r"C:\Users\user\Desktop\chromedriver_win32_new\chromedriver.exe") 
time.sleep(2)

# to get url
url = "https://www.guru99.com/"
driver.get(url)
time.sleep(2)

In [144]:
#Going to search bar and searching for selenium exception
ser_bar = driver.find_element_by_xpath("/html/body/div[1]/div/div/div/main/div/article/div/div[1]/div[1]/div[2]/div/div[1]/div/div/div/form/table/tbody/tr/td[1]/div/table/tbody/tr/td[1]/input")
ser_bar.send_keys("selenium exception handling")
ser_but = driver.find_element_by_xpath("/html/body/div[1]/div/div/div/main/div/article/div/div[1]/div[1]/div[2]/div/div[1]/div/div/div/form/table/tbody/tr/td[2]/button").click()
time.sleep(3)

In [ ]:
#Url of selenium exception handling page
urls = driver.find_element_by_xpath("//div[@class='gsc-expansionArea']//div//a")
page_url = urls.get_attribute("href")

driver.get(page_url)
time.sleep(5)

#Scraping data of names of exceptions
Name = []
for i in driver.find_elements_by_xpath("//table[@class='table table-striped']//tr//td[1]")[1:]:
    Name.append(i.text)
    
#Scraping data of descriptions of exceptions  
Description = []
for i in driver.find_elements_by_xpath("//table[@class='table table-striped']//tr//td[2]")[1:]:
    Description.append(i.text)

In [146]:
#DATA FRAMEING
Guru=pd.DataFrame({})
Guru['Name of Exception'] = Name
Guru['Description of Exception'] = Description
#Printing data frame
Guru

,Name of Exception,Description of Exception
0,ElementNotSelectableException,This Selenium exception occurs when an element...
1,NoSuchElementException,This Exception occurs if an element could not ...
2,NoSuchFrameException,This Exception occurs if the frame target to b...
3,NoAlertPresentException,This Exception occurs when you switch to no pr...
4,NoSuchWindowException,This Exception occurs if the window target to ...
5,StaleElementReferenceException,This Selenium exception occurs happens when th...
6,SessionNotFoundException,The WebDriver is acting after you quit the bro...
7,TimeoutException,Thrown when there is not enough time for a com...
8,WebDriverException,This Exception takes place when the WebDriver ...
9,ConnectionClosedException,This type of Exception takes place when there ...
10,ElementClickInterceptedException,The command may not be completed as the elemen...
11,ElementNotInteractableException,This Selenium exception is thrown when any ele...
12,ErrorInResponseException,This happens while interacting with the Firefo...
13,ErrorHandler.UnknownServerException,Exception is used as a placeholder in case if ...
14,ImeActivationFailedException,This expectation will occur when IME engine ac...
15,ImeNotAvailableException,It takes place when IME support is unavailable.
16,InsecureCertificateException,Navigation made the user agent to hit a certif...
17,InvalidArgumentException,It occurs when an argument does not belong to ...
18,InvalidCookieDomainException,This happens when you try to add a cookie unde...
19,InvalidCoordinatesException,This type of Exception matches an interacting ...
20,InvalidElementStateExceptio,It occurs when command can’t be finished when ...
21,InvalidSessionIdException,This Exception took place when the given sessi...
22,InvalidSwitchToTargetException,This occurs when the frame or window target to...
23,JavascriptException,This issue occurs while executing JavaScript g...
24,JsonException,It occurs when you afford to get the session w...
25,NoSuchAttributeException,This kind of Exception occurs when the attribu...
26,MoveTargetOutOfBoundsException,It takes place if the target provided to the A...
27,NoSuchContextException,ContextAware does mobile device testing.
28,NoSuchCookieException,This Exception occurs when no cookie matching ...
29,NotFoundException,This Exception is a subclass of WebDriverExcep...
30,RemoteDriverServerException,This Selenium exception is thrown when the ser...
31,ScreenshotException,It is not possible to capture a screen.
32,SessionNotCreatedException,It happens when a new session could not be suc...
33,UnableToSetCookieException,This occurs if a driver is unable to set a coo...
34,UnexpectedTagNameException,Happens if a support class did not get a web e...
35,UnhandledAlertException,This expectation occurs when there is an alert...
36,UnexpectedAlertPresentException,It occurs when there is the appearance of an u...
37,UnknownMethodException,This Exception happens when the requested comm...
38,UnreachableBrowserException,This Exception occurs only when the browser is...
39,UnsupportedCommandException,This occurs when remote WebDriver does n’t sen...

In [147]:
driver.close

Q4. Scrape the details of State-wise GDP of India from statisticstime.com.
Url = http://statisticstimes.com/
You have to find following details:
A) Rank
B) State
C) GSDP(18-19)
D) GSDP(17-18)
E) Share(2017)
F) GDP($ billion)
Note: - From statisticstimes home page you have to reach to economy page through code

In [27]:
# connect to webdriver
driver=webdriver.Chrome(r"C:\Users\user\Desktop\chromedriver_win32_new\chromedriver.exe") 
time.sleep(2)

# to get url
url = "http://statisticstimes.com/"
driver.get(url)
time.sleep(2)

In [28]:
#Clicking on economy section
economy = driver.find_element_by_xpath("//div[@class='navbar']//div[2]//button").click()

urls = driver.find_element_by_xpath("//div[@class='dropdown-content']//a[3]")
ineco_page = urls.get_attribute("href")
#Going to indian economy page
driver.get(ineco_page)  
time.sleep(5)

In [ ]:
#Creating empty list
Rank = []
State = []
GSDP_1 = []
GSDP_2 = []
Share = []
GDP = []

#get the url of page containing GDP of indian states
sta_GDP = driver.find_element_by_xpath("//ul[@style='list-style-type:none;margin-left:20px;']/li/a")
GDP_url = sta_GDP.get_attribute("href")

driver.get(GDP_url)
time.sleep(6)

#Scraping data of rank
for i in driver.find_elements_by_xpath("/html/body/div[3]/div[2]/div[5]/div[1]/div/table/tbody/tr[1]/td[1]"):
    Rank.append(i.text)

Rank

   
#Scraping data of state name
for i in driver.find_elements_by_xpath("//div[@id='table_id_wrapper']//tbody//tr//td[2]"):
    State.append(i.text)
State

    
# Scraping data of GSDP at current price (19-20)
for i in driver.find_elements_by_xpath("//div[@id='table_id_wrapper']//tbody//tr//td[3]"):
    GSDP_1.append(i.text)
GSDP_1

    
#Scraping data of GSDP at current price (18-19)
for i in driver.find_elements_by_xpath("//div[@id='table_id_wrapper']//tbody//tr//td[4]"):
    GSDP_2.append(i.text)

    
#Scraping data of Share(18-19)
for i in driver.find_elements_by_xpath("//div[@id='table_id_wrapper']//tbody//tr//td[5]"):
    Share.append(i.text)

    
#Scraping data of GDP($ billion)
for i in driver.find_elements_by_xpath("//div[@id='table_id_wrapper']//tbody//tr//td[6]"):
    GDP.append(i.text)

In [47]:
#creatng dataframe
df=pd.DataFrame({'Rank':Rank[:66],
                'State':State[:66],
                'GSDP(19-20)':GSDP_1[:66],
                'GSDP(18-19)':GSDP_2[:66],
                'Share(18-19)':Share,
                'GDP(Billion_$)':GDP})
df

,Rank,State,GSDP(19-20),GSDP(18-19),Share(18-19),GDP(Billion_$)
0,1,Maharashtra,-,"2,632,792",13.94%,399.921
1,2,Tamil Nadu,"1,845,853","1,630,208",8.63%,247.629
2,3,Uttar Pradesh,"1,687,818","1,584,764",8.39%,240.726
3,4,Gujarat,-,"1,502,899",7.96%,228.290
4,5,Karnataka,"1,631,977","1,493,127",7.91%,226.806
...,...,...,...,...,...,...
61,29,Manipur,"31,790","27,870",0.15%,4.233
62,30,Nagaland,-,"27,283",0.14%,4.144
63,31,Arunachal Pradesh,-,"24,603",0.13%,3.737
64,32,Mizoram,"26,503","22,287",0.12%,3.385
65,33,Andaman & Nicobar Islands,-,-,-,-

In [30]:
driver.close

Q5. Scrape the details of trending repositories on Github.com.
Url = https://github.com/
You have to find the following details:
A) Repository title
B) Repository description
C) Contributors count
D) Language used

In [72]:
# connect to web driver
driver=webdriver.Chrome(r"C:\Users\user\Desktop\chromedriver_win32_new\chromedriver.exe")  
time.sleep(2)

# Opening the github
url = "https://github.com/"
driver.get(url)

In [78]:
#Getting explore button and clicking on it
explore = driver.find_element_by_xpath("/html/body/div[1]/header/div/div[2]/nav/ul/li[4]/details")

#Selecting trending option
trend_url = driver.find_element_by_xpath("/html/body/div[1]/header/div/div[2]/nav/ul/li[4]/details/div/ul/li[5]/a")
urls = trend_url.get_attribute("href")
driver.get(urls)

# making empty lists    
repo_urls=[]
Contributors_count=[]
Language_used=[]
repo_title=[]
repo_desc=[]

#scraping repositories urls
repos=driver.find_elements_by_xpath("//h1[@class='h3 lh-condensed']/a")
for i in repos:
    repo_urls.append(i.get_attribute('href'))
time.sleep(2)    
    
#scraping repositories title
repo_title=[]
try:
    repos=driver.find_elements_by_xpath("//h1[@class='h3 lh-condensed']")
    for i in repos:
        repo_title.append(i.text)
except NoSuchElementException:#handling no such element exception
    repo_title.append('No details available')
time.sleep(3)
    

for i in repo_urls:
    driver.get(i)
    l=[]
    time.sleep(3)
     #scraping repositories discription
    try:          
        repo_desc.append(driver.find_element_by_xpath("/html/body/div[4]/div/main/div[1]/div[2]/div/p").text)
    except:
        repo_desc.append('-')
    
    #scraping contributors count
    try:
        count=driver.find_element_by_xpath("//h2[@class='h4 mb-3']/a[contains(text(),'Contributors')]/span")
        Contributors_count.append(count.text)
    except NoSuchElementException:#handling no such element exception
        Contributors_count.append('No details available')
    time.sleep(2)
    
     #scraping languages used   
    languages=driver.find_elements_by_xpath("//li[@class='d-inline']//a//span[1]")
    if languages:    
        for i in languages:
            l.append(i.text)
    else:
        l.append('No languages used')
    Language_used.append(l)   
    
time.sleep(2)   
#creating dataframe
df=pd.DataFrame({'Title':repo_title,
                'Description':repo_desc,
                'Contributors_count':Contributors_count,
                'Language_used':Language_used})
df

,Title,Description,Contributors_count,Language_used
0,rocboss / paopao-ce,"🔥A artistic ""twitter like"" community built on ...",4,"[Go, TypeScript]"
1,zijie0 / HumanSystemOptimization,健康学习到150岁 - 人体系统调优不完全指南,2,[No languages used]
2,Grasscutters / Grasscutter,A server software reimplementation for a certa...,86,[Java]
3,neondatabase / neon,The serverless open source alternative to AWS ...,27,"[Rust, Python, TLA, Shell, Makefile, Dockerfile]"
4,trekhleb / javascript-algorithms,📝 Algorithms and data structures implemented i...,192,[JavaScript]
5,requarks / wiki,Wiki.js | A modern and powerful wiki app built...,164,"[Vue, JavaScript, SCSS, HTML, Pug, Shell]"
6,smartcontractkit / full-blockchain-solidity-co...,"Learn Blockchain, Solidity, and Full Stack Web...",2,[No languages used]
7,hasinhayder / hydra,Hydra is a zero-config API boilerplate with La...,5,"[PHP, Blade]"
8,Asabeneh / 30-Days-Of-React,30 Days of React challenge is a step by step g...,8,"[JavaScript, HTML]"
9,livebud / bud,The Full-Stack Web Framework for Go,8,"[JavaScript, Go, TypeScript, HTML, CSS, Shell]"
10,TomSchimansky / CustomTkinter,A modern and customizable python UI-library ba...,5,[Python]
11,ripienaar / free-for-dev,"A list of SaaS, PaaS and IaaS offerings that h...","1,178",[HTML]
12,helix-editor / helix,A post-modern modal text editor.,226,"[Rust, Scheme, JavaScript, CSS, Handlebars, Ni..."
13,Cveinnt / LiveTerm,💻 Build terminal styled websites in minutes!,3,"[TypeScript, Shell, JavaScript, CSS, Dockerfile]"
14,BishopFox / sliver,Adversary Emulation Framework,40,[Go]
15,cotes2020 / jekyll-theme-chirpy,"A minimal, responsive, and powerful Jekyll the...",35,"[HTML, SCSS, JavaScript, Shell, Ruby]"
16,topjohnwu / Magisk,The Magic Mask for Android,238,"[C++, Kotlin, Java, Shell, Python, Makefile]"
17,eludadev / css-buttons,"100 Modern CSS Buttons, Free And Royalty Free.",2,"[CSS, HTML, Vue, JavaScript]"
18,neovim / neovim,Vim-fork focused on extensibility and usability,807,"[Vim Script, C, Lua, Python, CMake, Shell]"
19,skyline-emu / skyline,Run Nintendo Switch homebrew & games on your A...,16,"[C++, Kotlin]"
20,ageitgey / face_recognition,The world's simplest facial recognition api fo...,45,"[Python, Dockerfile, Makefile]"
21,qmk / qmk_firmware,Open-source keyboard firmware for Atmel AVR an...,"1,747","[C, Makefile, C++, Python, Shell, Roff]"
22,zju3dv / OnePose,"Code for ""OnePose: One-Shot Object Pose Estima...",No details available,[No languages used]
23,yangshun / tech-interview-handbook,💯 Curated interview preparation materials for ...,113,"[JavaScript, Python, HTML, CSS]"
24,coolsnowwolf / lede,Lean's OpenWrt source,292,"[C, Makefile, Shell, Roff, Perl, M4]"

In [79]:
driver.close

Q6. Scrape the details of top 100 songs on billiboard.com.
Url = https:/www.billboard.com/
You have to find the following details:
A) Song name
B) Artist name
C) Last week rank
D) Peak rank
E) Weeks on board
Note: - From the home page you have to click on the charts option then hot 100-page link through code.

In [2]:
# to get web drivers
driver=webdriver.Chrome(r"C:\Users\user\Desktop\chromedriver_win32_new\chromedriver.exe")  
time.sleep(2)

# Opening the billboard
url = "https://www.billboard.com/"
driver.get(url)
time.sleep(2)

In [3]:
#Clicking on charts
driver.find_element_by_xpath("/html/body/div[3]/header/div[1]/div/div/div[2]/div/nav/ul/li[1]").click()

In [4]:
# clicking view chart
driver.find_element_by_xpath("/html/body/div[3]/main/div[2]/div[1]/div[1]/div/div/div[3]/a").click()

In [22]:
#Creating empty list
Name = []
Artist = []
Last_week_rank = []
Peak_rank = []
Weeks_on_board = []

In [27]:
#scraping song names
try:
    names=driver.find_elements_by_xpath("//div[@class='o-chart-results-list-row-container']//h3")
    for i in names:
        Name.append(i.text)
except NoSuchElementException:       
    Name.append('No details available')
time.sleep(2)    
Name[::4][:100]

['As It Was',
 'First Class',
 'Wait For U',
 'About Damn Time',
 'Heat Waves',
 'Big Energy',
 'Me Porto Bonito',
 'Running Up That Hill (A Deal With God)',
 'Late Night Talking',
 'Stay',
 'Titi Me Pregunto',
 'Enemy',
 'Wasted On You',
 'Moscow Mule',
 'Ghost',
 'Boyfriend',
 'Woman',
 'Bad Habits',
 'Numb Little Bug',
 'Super Gremlin',
 'You Proof',
 'True Love',
 'Take My Name',
 'Shivers',
 'Sweetest Pie',
 'Party',
 'Bam Bam',
 'Thats What I Want',
 'Cold Heart (PNAU Remix)',
 'Despues de La Playa',
 'AA',
 'Trouble With A Heartbreak',
 'Puffin On Zootiez',
 'Provenza',
 'MAMIII',
 'Ojitos Lindos',
 'Cooped Up',
 "'Til You Can't",
 'N95',
 'Something In The Orange',
 'Music For A Sushi Restaurant',
 'Matilda',
 'Thousand Miles',
 "She's All I Wanna Be",
 'In A Minute',
 'Daylight',
 'Sleazy Flow',
 'Damn Strait',
 'Get Into It (Yuh)',
 'Efecto',
 'Silent Hill',
 'Die Hard',
 'Hold My Hand',
 '2step',
 'Fall In Love',
 'To The Moon!',
 'Slow Down Summer',
 'Little Freak',
 "See Wat I'm Sayin",
 'Die Young',
 'Grapejuice',
 'Un Ratito',
 'Tarot',
 "When You're Gone",
 'Satellite',
 'Like I Love Country Music',
 'What Happened To Virgil',
 'Never Say Never',
 'Thought You Should Know',
 'If I Was A Cowboy',
 'Potion',
 'Hotel Lobby (Unc And Phew)',
 'Right On',
 'Freaky Deaky',
 'Cinema',
 'Keep Driving',
 'Daydreaming',
 'Yo No Soy Celoso',
 'Flower Shops',
 'She Likes It',
 'Love Of My Life',
 'Ghost Story',
 'Rich Spirit',
 'La Corriente',
 'Neverita',
 'She Had Me At Heads Carolina',
 'Sunroof',
 'Boyfriends',
 'Circles Around This Town',
 'Dua Lipa',
 "F.N.F. (Let's Go)",
 'Handsomer',
 "I'm On One",
 'DFMU',
 'Andrea',
 'Love You Better',
 'Wild Hearts',
 'Last Night Lonely',
 '7500 OBO',
 'Until I Found You']

In [28]:
#scraping artist names
try:
    artist=driver.find_elements_by_xpath("//li[@class='lrv-u-width-100p']//span")
    for i in artist:
        Artist.append(i.text)
except NoSuchElementException:     
    Artist.append('-')
time.sleep(2)    
Artist[::7][:100]

['Harry Styles',
 'Jack Harlow',
 'Future Featuring Drake & Tems',
 'Lizzo',
 'Glass Animals',
 'Latto',
 'Bad Bunny & Chencho Corleone',
 'Kate Bush',
 'Harry Styles',
 'The Kid LAROI & Justin Bieber',
 'Bad Bunny',
 'Imagine Dragons X JID',
 'Morgan Wallen',
 'Bad Bunny',
 'Justin Bieber',
 'Dove Cameron',
 'Doja Cat',
 'Ed Sheeran',
 'Em Beihold',
 'Kodak Black',
 'Morgan Wallen',
 'Kanye West & XXXTENTACION',
 'Parmalee',
 'Ed Sheeran',
 'Megan Thee Stallion & Dua Lipa',
 'Bad Bunny & Rauw Alejandro',
 'Camila Cabello Featuring Ed Sheeran',
 'Lil Nas X',
 'Elton John & Dua Lipa',
 'Bad Bunny',
 'Walker Hayes',
 'Jason Aldean',
 'Future',
 'Karol G',
 'Becky G X Karol G',
 'Bad Bunny & Bomba Estereo',
 'Post Malone Featuring Roddy Ricch',
 'Cody Johnson',
 'Kendrick Lamar',
 'Zach Bryan',
 'Harry Styles',
 'Harry Styles',
 'The Kid LAROI',
 'Tate McRae',
 'Lil Baby',
 'Harry Styles',
 'SleazyWorld Go Featuring Lil Baby',
 'Scotty McCreery',
 'Doja Cat',
 'Bad Bunny',
 'Kendrick Lamar & Kodak Black',
 'Kendrick Lamar, Blxst & Amanda Reifer',
 'Lady Gaga',
 'Ed Sheeran Featuring Lil Baby',
 'Bailey Zimmerman',
 'JNR CHOI & Sam Tompkins',
 'Thomas Rhett',
 'Harry Styles',
 'Moneybagg Yo',
 'Sleepy Hallow Featuring 347aidan',
 'Harry Styles',
 'Bad Bunny',
 'Bad Bunny & Jhay Cortez',
 'Shawn Mendes',
 'Harry Styles',
 'Kane Brown',
 'Lil Durk Featuring Gunna',
 'Cole Swindell / Lainey Wilson',
 'Morgan Wallen',
 'Miranda Lambert',
 'Calvin Harris, Dua Lipa & Young Thug',
 'Quavo & Takeoff',
 'Lil Baby',
 'Tyga X Doja Cat',
 'Harry Styles',
 'Harry Styles',
 'Harry Styles',
 'Bad Bunny',
 'ERNEST Featuring Morgan Wallen',
 'Russell Dickerson & Jake Scott',
 'Harry Styles',
 'Carrie Underwood',
 'Kendrick Lamar',
 'Bad Bunny & Tony Dize',
 'Bad Bunny',
 'Cole Swindell',
 'Nicky Youre & dazy',
 'Harry Styles',
 'Maren Morris',
 'Jack Harlow',
 'Hitkidd & Glorilla',
 'Russ Featuring Ktlyn',
 'Future Featuring Drake',
 'Ella Mai',
 'Bad Bunny & Buscabulla',
 'Future',
 'Keith Urban',
 'Jon Pardi',
 'Tim McGraw',
 'Stephen Sanchez']

In [23]:
#scraping last week rank of the song
try:
    last_rank=driver.find_elements_by_xpath("//li[@class='o-chart-results-list__item // a-chart-color u-width-72 u-width-55@mobile-max u-width-55@tablet-only lrv-u-flex lrv-u-flex-shrink-0 lrv-u-align-items-center lrv-u-justify-content-center lrv-u-border-b-1 u-border-b-0@mobile-max lrv-u-border-color-grey-light u-background-color-white-064@mobile-max lrv-u-flex-grow-1']")
    for i in last_rank:
        Last_week_rank.append(i.text)
except NoSuchElementException:      
    Last_week_rank.append('-')
    time.sleep(2)    
Last_week_rank[::2][:100]

['1',
 '2',
 '3',
 '5',
 '6',
 '7',
 '10',
 '-',
 '4',
 '12',
 '16',
 '11',
 '23',
 '17',
 '18',
 '28',
 '19',
 '27',
 '35',
 '33',
 '26',
 '-',
 '48',
 '36',
 '40',
 '31',
 '37',
 '34',
 '38',
 '32',
 '51',
 '44',
 '39',
 '45',
 '47',
 '50',
 '43',
 '46',
 '20',
 '42',
 '8',
 '9',
 '52',
 '60',
 '53',
 '13',
 '-',
 '57',
 '58',
 '63',
 '49',
 '41',
 '86',
 '64',
 '65',
 '54',
 '66',
 '14',
 '-',
 '-',
 '15',
 '56',
 '55',
 '67',
 '21',
 '74',
 '69',
 '68',
 '62',
 '75',
 '-',
 '59',
 '71',
 '72',
 '22',
 '25',
 '24',
 '70',
 '82',
 '90',
 '29',
 '-',
 '61',
 '80',
 '77',
 '-',
 '-',
 '30',
 '88',
 '76',
 '-',
 '-',
 '83',
 '99',
 '87',
 '84',
 '-',
 '-',
 '-',
 '-']

In [24]:
#scraping number of weeks on board
try:
    weeks=driver.find_elements_by_xpath("//li[@class='o-chart-results-list__item // a-chart-color u-width-72 u-width-55@mobile-max u-width-55@tablet-only lrv-u-flex lrv-u-flex-shrink-0 lrv-u-align-items-center lrv-u-justify-content-center lrv-u-border-b-1 u-border-b-0@mobile-max lrv-u-border-color-grey-light u-background-color-white-064@mobile-max lrv-u-flex-grow-1']")
    for i in weeks:
        Weeks_on_board.append(i.text)
except NoSuchElementException:       #handling no such element exception
    Weeks_on_board.append('-')
time.sleep(2)    
Weeks_on_board[1::2][:100]

['9',
 '8',
 '5',
 '7',
 '72',
 '32',
 '4',
 '21',
 '2',
 '47',
 '4',
 '28',
 '29',
 '4',
 '36',
 '16',
 '44',
 '49',
 '18',
 '30',
 '3',
 '1',
 '9',
 '38',
 '12',
 '4',
 '13',
 '37',
 '39',
 '4',
 '21',
 '11',
 '5',
 '6',
 '16',
 '4',
 '3',
 '34',
 '3',
 '6',
 '2',
 '2',
 '6',
 '17',
 '8',
 '2',
 '1',
 '9',
 '26',
 '4',
 '3',
 '3',
 '4',
 '6',
 '5',
 '14',
 '15',
 '2',
 '1',
 '1',
 '2',
 '4',
 '4',
 '9',
 '2',
 '2',
 '12',
 '20',
 '4',
 '18',
 '1',
 '2',
 '8',
 '14',
 '2',
 '2',
 '2',
 '4',
 '19',
 '9',
 '2',
 '2',
 '3',
 '4',
 '4',
 '1',
 '1',
 '2',
 '19',
 '4',
 '1',
 '10',
 '5',
 '2',
 '4',
 '5',
 '1',
 '1',
 '1',
 '1']

In [25]:
#scraping song's peak rank
try:
    peak=driver.find_elements_by_xpath("//li[@class='o-chart-results-list__item // a-chart-bg-color a-chart-color u-width-72 u-width-55@mobile-max u-width-55@tablet-only lrv-u-flex lrv-u-flex-shrink-0 lrv-u-align-items-center lrv-u-justify-content-center lrv-u-background-color-grey-lightest lrv-u-border-b-1 u-border-b-0@mobile-max lrv-u-border-color-grey-light lrv-u-flex-grow-1']")
    for i in peak:
        Peak_rank.append(i.text)
except NoSuchElementException:       
    Peak_rank.append('-')
time.sleep(2)    
Peak_rank[1::2][:100]

['1',
 '1',
 '1',
 '4',
 '1',
 '3',
 '7',
 '8',
 '4',
 '1',
 '5',
 '5',
 '9',
 '4',
 '5',
 '16',
 '7',
 '2',
 '19',
 '3',
 '6',
 '22',
 '23',
 '4',
 '15',
 '14',
 '21',
 '8',
 '7',
 '6',
 '28',
 '32',
 '4',
 '25',
 '15',
 '26',
 '29',
 '18',
 '3',
 '40',
 '8',
 '9',
 '15',
 '44',
 '14',
 '13',
 '47',
 '48',
 '49',
 '34',
 '7',
 '5',
 '53',
 '51',
 '55',
 '38',
 '43',
 '14',
 '59',
 '60',
 '15',
 '16',
 '18',
 '38',
 '21',
 '66',
 '22',
 '27',
 '12',
 '53',
 '71',
 '59',
 '13',
 '43',
 '22',
 '25',
 '24',
 '22',
 '64',
 '80',
 '29',
 '72',
 '13',
 '32',
 '31',
 '86',
 '87',
 '30',
 '52',
 '21',
 '91',
 '40',
 '11',
 '94',
 '51',
 '12',
 '97',
 '98',
 '99',
 '100']

In [29]:
df=pd.DataFrame({'Song_Name':Name[::4][:100],
                'Artist_Name':Artist[::7][:100],
                'Last_week_rank':Last_week_rank[::2][:100],
                'Peak':Peak_rank[1::2][:100],
                'Weeks_on_chart':Weeks_on_board[1::2][:100]})
df

,Song_Name,Artist_Name,Last_week_rank,Peak,Weeks_on_chart
0,As It Was,Harry Styles,1,1,9
1,First Class,Jack Harlow,2,1,8
2,Wait For U,Future Featuring Drake & Tems,3,1,5
3,About Damn Time,Lizzo,5,4,7
4,Heat Waves,Glass Animals,6,1,72
...,...,...,...,...,...
95,Love You Better,Future,84,12,5
96,Wild Hearts,Keith Urban,-,97,1
97,Last Night Lonely,Jon Pardi,-,98,1
98,7500 OBO,Tim McGraw,-,99,1
99,Until I Found You,Stephen Sanchez,-,100,1

In [45]:
driver.close

Q7. Scrape the details of Data science recruiters from naukri.com.
Url = https://www.naukri.com/
You have to find the following details:
A) Name
B) Designation
C) Company
D) Skills they hire for
E) Location
Note: - From naukri.com homepage click on the recruiters option and the on the search pane type Data science and
click on search. All this should be done through code

In [47]:
# to get web drivers
driver=webdriver.Chrome(r"C:\Users\user\Desktop\chromedriver_win32_new\chromedriver.exe")  
time.sleep(2)

# Opening the naukri.com
url = "https://www.naukri.com/"
driver.get(url)
time.sleep(2)

In [52]:
#Fetching urls for recruiter page
rec = driver.find_element_by_xpath("/html/body/div/div[2]/div[1]/div/ul/li[1]/a")
page_url = rec.get_attribute("href")

driver.get(page_url)
time.sleep(3)

In [54]:
#clicking on recruiters link
recruiters=driver.find_element_by_xpath("//a[@title='Search Recruiters']")
driver.get(recruiters.get_attribute('href'))
time.sleep(1)

In [55]:
#accesing search bar
search=driver.find_element_by_xpath("//input[@class='sugInp']")
search.send_keys("Data Science")
time.sleep(1)

In [56]:
#clicking on search button
button=driver.find_element_by_xpath("//button[@id='qsbFormBtn']")
button.click()
time.sleep(1)

In [57]:
#Creating empty list
Name = []
Designation = []
Company = []
Skills = []
Location = []

In [58]:
#Scraping data of Names
for i in driver.find_elements_by_xpath("//span[@class='fl ellipsis']"):
    Name.append(i.text)
time.sleep(5)


#Scraping data of Designation
for i in driver.find_elements_by_xpath("//span[@class='ellipsis clr']"):
    Designation.append(i.text)
time.sleep(5)

#Scraping data of company name
for i in driver.find_elements_by_xpath("//div[@class='vcard']//p[1]/a[2]"):
    Company.append(i.text)
time.sleep(5)
    
#scraping data of Skills 
for i in driver.find_elements_by_xpath("//div[@class='hireSec highlightable']"):
    try:
        if i.text == "Not Specified": raise NoSuchElementException
        Skills.append(i.text)
    except NoSuchElementException:
        Skills.append('-')
    time.sleep(5)

#Scraping data of locations
for i in driver.find_elements_by_xpath("//div[@class='vcard']//p[1]//span"):
    Location.append(i.text)
time.sleep(5)

In [61]:
#DATA FRAMEING
Naukri=pd.DataFrame({})
Naukri['Name'] = Name[:50]
Naukri['Designation'] = Designation[:50]
Naukri['Company'] = Company[:50]
Naukri['Skills'] = Skills[:50]
Naukri['Location'] = Location[:50]
Naukri

,Name,Designation,Company,Skills,Location
0,Aakash Harit,HR Manager,Data Science Network,"Classic ASP Developer, Internet Marketing Prof...",Aakash Harit
1,shravan Kumar Gaddam,Company Recruiter,Shore Infotech India Pvt. Ltd,".Net, Java, Data Science, Linux Administration...",HR Manager
2,MARSIAN Technologies LLP,Company HR,MARSIAN Technologies LLP,"Data Science, Artificial Intelligence, Machine...",Delhi
3,Anik Agrawal,Company Recruiter,Enerlytics Software Solutions Pvt Ltd,"Mean Stack, javascript, angularjs, mongodb, We...",shravan Kumar Gaddam
4,subhas patel,Founder CEO,LibraryXProject,"Hadoop, Spark, Digital Strategy, Data Architec...",Company Recruiter
5,Abhishek - Only Analytics Hiring - India and,Recruitment Lead Consultant,Apidel Technologies Division of Transpower,"Analytics, Business Intelligence, Business Ana...",Hyderabad / Secunderabad
6,Institute for Financial Management and Resear,Programme Manager,IFMR,Data Science,MARSIAN Technologies LLP
7,Balu Ramesh,HR Administrator,Techvantage Systems Pvt Ltd,"Machine Learning, algorithms, Go Getter, Compu...",Company HR
8,Asif Lucknowi,Director,Weupskill- Live Wire India,"Technical Training, Software Development, Pres...",Pune
9,InstaFinancials,Human Resource,CBL Data Science Private Limited,"Software Development, It Sales, Account Manage...",Anik Agrawal
10,Priyanka Akiri,HR Manager,Infinitive Software Solutions,"Oracle Dba, Data Science, Data Warehousing, ET...",Company Recruiter
11,Kalpana Dumpala,Executive Hiring,Innominds Software,"Qa, Ui/ux, Java Developer, Java Architect, C++...",Ahmedabad
12,Mubarak,Company HR,MoneyTap,"Business Intelligence, Data Warehousing, Data ...",subhas patel
13,Kushal Rastogi,Company HR,QuantMagnum Technologies Pvt. Ltd.,"Office Administration, Hr Administration, tele...",Founder CEO
14,Mahesh Babu Channa,HR Team Lead,SocialPrachar.com,"Social Media, digital media maketing, seo, smm...",UK - (london)
15,Kapil Devang,HR Manager,BISP Solutions,"Big Data, Hadoop, Data Analytics, Data Science",Abhishek - Only Analytics Hiring - India and
16,Sakshi Chhikara,Assistant Manager HR,BIZ INFOTECNO PRIVATE LIMITED,"React.js, Data Science, Java, Front End, Busin...",Recruitment Lead Consultant
17,Ruchi Dhote,Senior Executive Talent Acquisition,Bristlecone India Ltd,"Qlikview, Qlik Sense, Microsoft Azure, Power B...",Vadodara / Baroda
18,Manisha Yadav,HR Executive,Easi Tax,"Telecalling, Client Interaction, Marketing, Re...",Institute for Financial Management and Resear
19,Riya Rajesh,Manager Talent Acquisition,Novelworx Digital Solutions,Data Science,Programme Manager
20,Rashmi Bhattacharjee,HR Head,AXESTRACK SOFTWARE SOLUTIONS PRIVATE...,"Corporate Sales, Software Development, Softwar...",Chennai
21,Faizan Kareem,HR MANAGER,FirstTech Consaltants Pvt.Ltd,"Data Analytics, Data Science, Machine Learning...",Balu Ramesh
22,Rithika dadwal,HR Recruiter,Affine Analytics,"Data Science, Machine Learning, Python, R, Dee...",HR Administrator
23,Sandhya Khandagale,HR Recruiter,Compumatrice Multimedia Pvt Ltd,"Big Data, Data Science, Artificial Intelligenc...",Trivandrum
24,Shaun Rao,Manager Human Resources,Exela Technologies,"Java, Net, Angularjs, Hr, Infrastructure, Mana...",Asif Lucknowi
25,Hemant Jog,Company Recruiter,Hexaware Technologies Ltd.,"Big Data, spark, scala, hadoop, hive, Data War...",Director
26,Azahar Shaikh,Company Recruiter,NEAL ANALYTICS SERVICES PVT LTD,"Data Science, Artificial Intelligence, Machine...",Indore
27,Manas,Lead Talent acquisition,Autumn Leaf Consulting Services Private...,"Software Architecture, Vp Engineering, Product...",InstaFinancials
28,kumar,Proprietor,trainin,"Data Science, Hadoop, Rpas, Devops, Python, Aw...",Human Resource
29,Sunil Vedula,CEO,Nanoprecise Sci Corp,"Signal Processing, Machine Learning, Neural Ne...",Bengaluru / Bangalore
30,Rajat Kumar,Founder CEO,R.S Consultancy &amp; Services,"Web Technologies, Project Management, Software...",Priyanka Akiri
31,Dhruv Dev Dubey,Company Recruitment Head,Confidential,"Server Administartion, Verilog, Vhdl, Digital ...",HR Manager
32,Jayanth N,Project Manager,"Dollarbird Information Services Pvt, Ltd","Data Analytics, Managed Services, Team Leading...",Hyderabad
33,Avodha,Business Development Associate,Nikitha Palaparthi,"Ethical Hacking, Security Operations Center, S...",Kalpana Dumpala
34,Ravi Dubey,Recruitment Manager,HyrEzy Talent Solutions LLP,Walmart Interra Skeps Expressstores indifi whi...,Executive Hiring
35,Priya Khare,Senior Manager,Independent Consultant,"Data Science, Artificial Intelligence, analyti...",Hyderabad / Secunderabad
36,Amit Sharma,Consultant,ASCO consulting,"Machine Learning, Artificial Intelligence, Dat...",Mubarak
37,Kanan,senior technology instructor,NY INST,"C, C++, Artificial Intelligence, Python, Php, ...",Company HR
38,Shashikant Chaudhary,HR Recruiter/HR Excutive,3D India Staffing Research &amp; Consulting...,"Relationship Management, Retail Sales, Private...",Bengaluru / Bangalore
39,Brad,"Manager, Technical Recruiting",O.C. Tanner,"Data Science, Software Engineering",Kushal Rastogi
40,Rutuja Pawar,Technical Recruiter,Demand Matrix,"Data Science, Big Data Analytics, Digital Mark...",Company HR
41,Madhusudhan Sridhar,Erp Implementer,MADHUSUDHAN SRIDHAR,"Data Science, Recruitment, Salary",Mumbai
42,Ankit Sinha,Head Analytics,Suntech Global,"B.Tech, Tableau, Statistics, R, Analytics, Tim...",Mahesh Babu Channa
43,Gaurav Chouhan,Chief Technical Officer,Strategic Consulting Lab,"Software Development, Business Intelligence, B...",HR Team Lead
44,Rashi Kacker,Sr Product Manager,Impel Labs Pvt. Ltd.,"Data Science, Node.js, Angularjs",Hyderabad / Secunderabad
45,Ashwini,Director Global Delivery,MRP Advisers,"Data Science, Media Marketing, Resource Planni...",Kapil Devang
46,Balaji Kolli,Co Founder,Saras Solutions India Pvt Ltd,"Data Analysis, Learning, Data Science, Compute...",HR Manager
47,Rajani Nagaraj,HR Manager,WildJasmine,"Java, Hadoop, R, Machine Learning, Spark, Flum...",Bhopal
48,ROHIT Kumar,Architect,LNT Private Limited,"Software Development, Core Java, Unit Testing,...",Sakshi Chhikara
49,Amir Chowdhury,Managing Partner,Granular.ai,"Machine Learning, Data Science, Product Manage...",Assistant Manager HR

In [31]:
driver.close

Q8. Scrape the details of Highest selling novels.
Url = https://www.theguardian.com/news/datablog/2012/aug/09/best-selling-books-all-time-fifty-shades-greycompare/
You have to find the following details:
A) Book name
B) Author name
C) Volumes sold
D) Publisher
E) Genre

In [62]:
# to get web drivers
driver=webdriver.Chrome(r"C:\Users\user\Desktop\chromedriver_win32_new\chromedriver.exe")
time.sleep(2)

# Opening the theguardian.com
url = "https://www.theguardian.com/news/datablog/2012/aug/09/best-selling-books-all-time-fifty-shades-grey-compare"
driver.get(url)
time.sleep(2)

In [63]:
#Creating empty list
Book_name = []
Author = []
Volumes_sold = []
Publisher = []
Genre = []

In [64]:
#scraping data of book names
for i in driver.find_elements_by_xpath("//tbody//tr/td[2]"):
    Book_name.append(i.text)

    
#Scraping data of author names
for i in driver.find_elements_by_xpath("//tbody/tr/td[3]"):
    try:
        if i.text == '0' : raise NoSuchElementException
        Author.append(i.text)
    except NoSuchElementException:
        Author.append('-')
time.sleep(1)


#Scraping data of volumes sold
for i in driver.find_elements_by_xpath("//tbody/tr/td[4]"):
    Volumes_sold.append(i.text)

    
#Scraping data of publisher names
for i in driver.find_elements_by_xpath("//tbody/tr/td[5]"):
    Publisher.append(i.text)

    
#Scraping data of genre
for i in driver.find_elements_by_xpath("//tbody/tr/td[6]"):
    Genre.append(i.text)

In [65]:
#DATA FRAMEING
Novel=pd.DataFrame({})
Novel['Book Name'] = Book_name
Novel['Author'] = Author
Novel['Volume sold'] = Volumes_sold
Novel['Publisher'] = Publisher
Novel['Genre'] = Genre
Novel

,Book Name,Author,Volume sold,Publisher,Genre
0,"Da Vinci Code,The","Brown, Dan","5,094,805",Transworld,"Crime, Thriller & Adventure"
1,Harry Potter and the Deathly Hallows,"Rowling, J.K.","4,475,152",Bloomsbury,Children's Fiction
2,Harry Potter and the Philosopher's Stone,"Rowling, J.K.","4,200,654",Bloomsbury,Children's Fiction
3,Harry Potter and the Order of the Phoenix,"Rowling, J.K.","4,179,479",Bloomsbury,Children's Fiction
4,Fifty Shades of Grey,"James, E. L.","3,758,936",Random House,Romance & Sagas
...,...,...,...,...,...
95,"Ghost,The","Harris, Robert","807,311",Random House,General & Literary Fiction
96,Happy Days with the Naked Chef,"Oliver, Jamie","794,201",Penguin,Food & Drink: General
97,"Hunger Games,The:Hunger Games Trilogy","Collins, Suzanne","792,187",Scholastic Ltd.,Young Adult Fiction
98,"Lost Boy,The:A Foster Child's Search for the L...","Pelzer, Dave","791,507",Orion,Biography: General
99,Jamie's Ministry of Food:Anyone Can Learn to C...,"Oliver, Jamie","791,095",Penguin,Food & Drink: General

In [32]:
driver.close

Q9. Scrape the details most watched tv series of all time from imdb.com.
Url = https://www.imdb.com/list/ls095964455/
You have to find the following details:
A) Name
B) Year span
C) Genre
D) Run time
E) Ratings
F) Votes

In [66]:
# to get web drivers
driver=webdriver.Chrome(r"C:\Users\user\Desktop\chromedriver_win32_new\chromedriver.exe")
time.sleep(2)

# Opening the imdb.com
url = "https://www.imdb.com/list/ls095964455"
driver.get(url)
time.sleep(2)

In [67]:
#Creating empty lists.
Name = []
Year_span = []
Genre = []
Run_time = []
Ratings = []
Votes = []

In [68]:
#Scraping data of Names
for i in driver.find_elements_by_xpath("//h3[@class='lister-item-header']/a"):
    Name.append(i.text)

    
#Scraping data of Year span
for i in driver.find_elements_by_xpath("//span[@class='lister-item-year text-muted unbold']"):
    Year_span.append(i.text)

    
#Scraping data of genre
for i in driver.find_elements_by_xpath("//span[@class='genre']"):
    Genre.append(i.text)

    
#Scraping data of Run time
for i in driver.find_elements_by_xpath("//span[@class='runtime']"):
    Run_time.append(i.text)

    
#Scraping data of Ratings
for i in driver.find_elements_by_xpath("//div[@class='ipl-rating-star small']//span[2]"):
    Ratings.append(i.text)

    
#Scraping data of votes
for i in driver.find_elements_by_xpath("//div[@class='lister-item-content']//p[4]/span[2]"):
    Votes.append(i.text)

In [70]:
#DATA FRAMEING
IMDB=pd.DataFrame({})
IMDB['Name'] = Name
IMDB['Year Span'] = Year_span
IMDB['Genre'] = Genre
IMDB['Run Time'] = Run_time
IMDB['Ratings'] = Ratings
IMDB['Votes'] = Votes
IMDB

,Name,Year Span,Genre,Run Time,Ratings,Votes
0,Game of Thrones,(2011–2019),"Action, Adventure, Drama",57 min,9.2,"1,990,075"
1,Stranger Things,(2016– ),"Drama, Fantasy, Horror",51 min,8.7,"1,007,012"
2,The Walking Dead,(2010–2022),"Drama, Horror, Thriller",44 min,8.2,"947,655"
3,13 Reasons Why,(2017–2020),"Drama, Mystery, Thriller",60 min,7.5,"283,128"
4,The 100,(2014–2020),"Drama, Mystery, Sci-Fi",43 min,7.6,"242,938"
...,...,...,...,...,...,...
95,Reign,(2013–2017),"Drama, Fantasy",42 min,7.4,"48,773"
96,A Series of Unfortunate Events,(2017–2019),"Adventure, Comedy, Drama",50 min,7.8,"59,422"
97,Criminal Minds,(2005–2020),"Crime, Drama, Mystery",42 min,8.1,"189,872"
98,Scream: The TV Series,(2015–2019),"Comedy, Crime, Drama",45 min,7.1,"40,202"
99,The Haunting of Hill House,(2018),"Drama, Horror, Mystery",572 min,8.6,"227,948"

In [33]:
driver.close

Q10. Details of Datasets from UCI machine learning repositories.
Url = https://archive.ics.uci.edu/
You have to find the following details:
A) Dataset name
B) Data type
C) Task
D) Attribute type
E) No of instances
F) No of attribute
G) Year
Note: - from the home page you have to go to the ShowAllDataset page through code.

In [71]:
# to get web drivers
driver=webdriver.Chrome(r"C:\Users\user\Desktop\chromedriver_win32_new\chromedriver.exe")
time.sleep(2)

# Opening the uci.com
url = "https://archive.ics.uci.edu/"
driver.get(url)
time.sleep(2)

In [72]:
#Finding view all dataset button
view_dataset = driver.find_element_by_xpath("//tbody[1]//tr/td[2]/span[2]/a")    
page_url = view_dataset.get_attribute("href")
driver.get(page_url)
time.sleep(5)

#Getting page urls containing list of all datasets
all_lst = driver.find_element_by_xpath("/html/body/table[2]/tbody/tr/td[2]/table[1]/tbody/tr/td[2]/p/a")  
lst_url = all_lst.get_attribute("href")           
driver.get(lst_url)
time.sleep(5)

#fetching url for each dataset
data_url = driver.find_elements_by_xpath("//p[@class='normal']//b/a")    

urls = []     
for i in data_url:
    urls.append(i.get_attribute("href"))

In [78]:
#table view
table = driver.find_element_by_xpath('/html/body/table[2]/tbody/tr/td[2]/table[1]/tbody/tr/td[2]/p/a')
table.click()

In [79]:
#Creating empty list
Data_name = []
Data_type = []
Task = []
Attr_type = []
Instances = []
n_attributes = []
Year = []

In [80]:
#Scraping requiredinfo from urls
for i in urls:
    driver.get(i)
    time.sleep(3)
    
    
    #Scraping Dataset name
    try: 
        ds_name = driver.find_element_by_xpath("//span[@class='heading']")
        Data_name.append(ds_name.text)
    except NoSuchElementException:
        Data_name.append('-')
    time.sleep(1)
    
    
    #Scraping data type
    try:
        dtype = driver.find_element_by_xpath("//table[@border='1']//tbody/tr/td[2]")
        if dtype.text == "N/A": raise NoSuchElementException
        Data_type.append(dtype.text)
    except NoSuchElementException:
        Data_type.append('-')
    time.sleep(1)
    
    
    #Scraping Attribute type
    try:
        atype = driver.find_element_by_xpath("//table[@border='1']//tbody/tr[2]/td[2]")
        if atype.text == "N/A": raise NoSuchElementException
        Attr_type.append(atype.text)
    except NoSuchElementException:
        Attr_type.append('-')
    time.sleep(1)
    
    
    #scraping Task
    try:
        task = driver.find_element_by_xpath("//table[@border='1']//tbody/tr[3]/td[2]")
        if task.text == "N/A": raise NoSuchElementException
        Task.append(task.text)
    except NoSuchElementException:
        Task.append('-')
    time.sleep(1)
    
    
    #Scraping No of instances
    try:
        inst = driver.find_element_by_xpath("//table[@border='1']//tbody/tr/td[4]")
        if inst.text == "N/A": raise NoSuchElementException
        Instances.append(inst.text)
    except NoSuchElementException:
        Instances.append('-')
    time.sleep(1)
    
    
    #Scraping  No of attribute
    try:
        attr = driver.find_element_by_xpath("//table[@border='1']//tbody/tr[2]/td[4]")
        if attr.text == "N/A": raise NoSuchElementException
        n_attributes.append(attr.text)
    except NoSuchElementException:
        n_attributes.append('-')
    time.sleep(1)
    
    
    #scraping year
    try:
        year = driver.find_element_by_xpath("//table[@border='1']//tbody/tr[2]/td[6]")
        if year.text == "N/A": raise NoSuchElementException
        Year.append(year.text[:4])
    except NoSuchElementException:
        Year.append('-')
    time.sleep(1)

In [81]:
#DATA FRAMEING
UCI=pd.DataFrame({})
UCI['Data Name'] = Data_name
UCI['Data Type'] = Data_type
UCI['Task'] = Task
UCI['Attribute type'] = Attr_type
UCI['No of instance'] = Instances
UCI['No of attributes'] = n_attributes
UCI['Year'] = Year
UCI

,Data Name,Data Type,Task,Attribute type,No of instance,No of attributes,Year
0,2.4 GHZ Indoor Channel Measurements Data Set,Multivariate,Classification,Real,7840,5,2018
1,"3D Road Network (North Jutland, Denmark) Data Set","Sequential, Text","Regression, Clustering",Real,434874,4,2013
2,3W dataset Data Set,"Multivariate, Time-Series","Classification, Clustering","Integer, Real",1984,8,2019
3,9mers from cullpdb Data Set,Sequential,"Classification, Regression",Real,158716,4,2021
4,: Simulated Data set of Iraqi tourism places D...,Multivariate,"Classification, Clustering",-,232,16,2020
...,...,...,...,...,...,...,...
617,Youtube cookery channels viewers comments in H...,"Multivariate, Text",Classification,-,9800,3,2019
618,YouTube Multiview Video Games Dataset Data Set,"Multivariate, Text","Classification, Clustering","Integer, Real",120000,1000000,2013
619,YouTube Spam Collection Data Set,Text,Classification,-,1956,5,2017
620,Z-Alizadeh Sani Data Set,-,Classification,"Integer, Real",303,56,2017
621,Zoo Data Set,Multivariate,Classification,"Categorical, Integer",101,17,1990

In [82]:
driver.close